#!/usr/bin/env bash
#
# Configuration collection functions
# Collects user input for devcontainer setup
#

# Collect all user configuration
# Populates global variables for .env file generation
collect_user_configuration() {
    echo -e "${GREEN}Step 2: Configuration${NC}"
    echo ""
    echo "I'll ask you a few questions to set up your environment."
    echo ""

    # 1. Anthropic API Key
    echo -e "${YELLOW}1. Anthropic API Key${NC}"
    echo "   Get your key from: https://console.anthropic.com/settings/keys"
    read -p "   Enter your API key: " -r ANTHROPIC_AUTH_TOKEN

    # Validate API key format
    if ! validate_api_key "$ANTHROPIC_AUTH_TOKEN"; then
        exit 1
    fi
    echo ""

    # 2. Git configuration
    echo -e "${YELLOW}2. Git Configuration${NC}"
    read -p "   Your name: " -r GIT_USER_NAME
    read -p "   Your email: " -r GIT_USER_EMAIL
    echo ""

    # 3. Firewall mode
    echo -e "${YELLOW}3. Firewall Configuration${NC}"
    echo "   Audit mode: Logs all traffic, doesn't block (recommended for first use)"
    echo "   Enforce mode: Blocks non-whitelisted traffic (more secure)"
    if prompt_yes_no "   Start in audit mode?"; then
        FIREWALL_MODE="audit"
    else
        FIREWALL_MODE="enforce"
    fi
    echo ""
}

# Generate .env file from collected configuration
# Args: None (uses global variables from collect_user_configuration)
generate_env_file() {
    echo -e "${GREEN}Step 3: Generating configuration files...${NC}"
    echo ""

    # Create .env file
    cat > .devcontainer/.env <<EOF
# ═══════════════════════════════════════════════════════════════════════════════
# WFC DevContainer Environment Configuration
# ═══════════════════════════════════════════════════════════════════════════════
#
# Generated by setup.sh on $(date)
# DO NOT commit .env to version control (it's in .gitignore)
#

# ────────────────────────────────────────────────────────────────────────────────
# Firewall Configuration
# ────────────────────────────────────────────────────────────────────────────────

# Firewall mode: "audit" or "enforce"
# - audit:   Log all traffic, don't block (useful for seeing what Claude needs)
# - enforce: Block non-whitelisted traffic (production security mode)
FIREWALL_MODE=$FIREWALL_MODE

# ────────────────────────────────────────────────────────────────────────────────
# Claude Code Configuration
# ────────────────────────────────────────────────────────────────────────────────

# Anthropic API Key (REQUIRED)
# Get your key from: https://console.anthropic.com/settings/keys
ANTHROPIC_AUTH_TOKEN=$ANTHROPIC_AUTH_TOKEN

# ────────────────────────────────────────────────────────────────────────────────
# Git Configuration
# ────────────────────────────────────────────────────────────────────────────────
GIT_AUTHOR_NAME=$GIT_USER_NAME
GIT_AUTHOR_EMAIL=$GIT_USER_EMAIL
GIT_COMMITTER_NAME=$GIT_USER_NAME
GIT_COMMITTER_EMAIL=$GIT_USER_EMAIL

# ────────────────────────────────────────────────────────────────────────────────
# SSH Key Forwarding (for Git operations)
# ────────────────────────────────────────────────────────────────────────────────
# SSH_AUTH_SOCK should be set automatically by Docker Compose
# If not, set it to your SSH agent socket path
# SSH_AUTH_SOCK=/tmp/.ssh-auth-sock

# ────────────────────────────────────────────────────────────────────────────────
# Build Performance Optimization
# ────────────────────────────────────────────────────────────────────────────────

# Enable Docker BuildKit for faster, more efficient builds
# BuildKit provides better caching, parallel build stages, and reduced image sizes
# Impact: 50-70% faster rebuilds
DOCKER_BUILDKIT=1

# Enable BuildKit for Docker Compose builds
# Works in conjunction with DOCKER_BUILDKIT
COMPOSE_DOCKER_CLI_BUILD=1

# Maximum number of parallel build stages
# Higher values speed up multi-stage builds on multi-core systems
# Recommended: 10 for most systems, adjust based on CPU cores
COMPOSE_PARALLEL_LIMIT=10
EOF

    echo -e "${GREEN}✓${NC} Created .env file"
    echo ""
}
