#!/usr/bin/env bash
#
# Folder mounting configuration
# Handles project folder mounting setup
#

# Collect folder mount configuration
# Populates PROJECT_MOUNTS array
collect_mount_configuration() {
    echo -e "${YELLOW}4. Project Folders${NC}"
    echo "   Which folder(s) should be mounted into the container?"
    echo "   This is where your code will be (accessible at /workspace inside container)"
    echo ""
    echo "   Current directory: $(pwd)"
    echo ""

    PROJECT_MOUNTS=()

    # Ask about current directory
    if prompt_yes_no "   Mount current directory?"; then
        PROJECT_MOUNTS+=("$(pwd):/workspace/app:cached")
        echo "   ✓ Will mount: $(pwd) → /workspace/app"
    else
        read -p "   Enter project folder path: " -r PROJECT_PATH
        if validate_directory "$PROJECT_PATH"; then
            PROJECT_MOUNTS+=("$PROJECT_PATH:/workspace/app:cached")
            echo "   ✓ Will mount: $PROJECT_PATH → /workspace/app"
        else
            echo "   Will use current directory instead"
            PROJECT_MOUNTS+=("$(pwd):/workspace/app:cached")
        fi
    fi
    echo ""

    # Ask about additional mounts
    echo "   Mount additional folders? (e.g., other projects, shared libraries)"
    if prompt_yes_no "   Add more folders?" "N"; then
        while true; do
            read -p "   Folder path (or press Enter to finish): " -r EXTRA_PATH
            if [[ -z "$EXTRA_PATH" ]]; then
                break
            fi

            if validate_directory "$EXTRA_PATH"; then
                read -p "   Mount point inside container (default: /workspace/repos/$(basename "$EXTRA_PATH")): " -r MOUNT_POINT
                if [[ -z "$MOUNT_POINT" ]]; then
                    MOUNT_POINT="/workspace/repos/$(basename "$EXTRA_PATH")"
                fi
                PROJECT_MOUNTS+=("$EXTRA_PATH:$MOUNT_POINT:cached")
                echo "   ✓ Will mount: $EXTRA_PATH → $MOUNT_POINT"
            fi
            echo ""
        done
    fi
    echo ""
}

# Generate docker-compose.override.yml with mount configuration
# Args: None (uses global PROJECT_MOUNTS array)
generate_mount_config() {
    echo "   Creating docker-compose.override.yml..."

    cat > .devcontainer/docker-compose.override.yml <<EOF
# Docker Compose Override - Volume Mounts
# Generated by setup.sh on $(date)

services:
  app:
    volumes:
EOF

    # Add each mount to the override file
    for mount in "${PROJECT_MOUNTS[@]}"; do
        echo "      - $mount" >> .devcontainer/docker-compose.override.yml
    done

    echo ""
    echo -e "${GREEN}✓${NC} Created docker-compose.override.yml with ${#PROJECT_MOUNTS[@]} mount(s)"
    echo ""
}
