#!/usr/bin/env bash
#
# Post-Start Script - Runs every time the container starts
# Verifies SSH key forwarding, network access, and package manager connectivity
#

set -euo pipefail

echo "Verifying WFC DevContainer connectivity..."

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
RED='\033[0;31m'
NC='\033[0m'

# ────────────────────────────────────────────────────────────────────────────────
# Verify SSH + GitHub Authentication
# ────────────────────────────────────────────────────────────────────────────────
echo -e "${BLUE}► Checking SSH access...${NC}"

GIT_SSH_OK=false

# Method 1: SSH agent forwarding from host
if [[ -n "${SSH_AUTH_SOCK:-}" ]] && ssh-add -l &>/dev/null; then
    echo -e "${GREEN}✓${NC} SSH agent forwarding active"
    ssh-add -l | head -3
    GIT_SSH_OK=true
fi

# Method 2: Container-local keypair (generated by post-create)
if [[ "$GIT_SSH_OK" != "true" ]] && [[ -f ~/.ssh/id_ed25519 ]]; then
    echo -e "${GREEN}✓${NC} Container SSH keypair available (~/.ssh/id_ed25519)"
    GIT_SSH_OK=true
fi

# Test actual GitHub SSH connection
if [[ "$GIT_SSH_OK" == "true" ]]; then
    echo -e "${BLUE}► Testing GitHub SSH connection...${NC}"
    if timeout 5 ssh -o StrictHostKeyChecking=accept-new -o BatchMode=yes git@github.com 2>&1 | grep -q "successfully authenticated"; then
        echo -e "${GREEN}✓${NC} GitHub SSH access working"
    else
        echo -e "${YELLOW}⚠${NC} GitHub SSH not authenticated — key may not be added to GitHub"
        echo -e "  ${YELLOW}Add key: gh ssh-key add ~/.ssh/id_ed25519.pub --title wfc-devcontainer${NC}"
    fi
else
    echo -e "${YELLOW}⚠${NC} No SSH keys available — git will use HTTPS"
    echo -e "  ${YELLOW}Generate keypair: ssh-keygen -t ed25519 -C wfc-devcontainer${NC}"
fi

# Check GitHub CLI auth
echo -e "${BLUE}► Checking GitHub CLI...${NC}"
if command -v gh &>/dev/null && gh auth status &>/dev/null; then
    echo -e "${GREEN}✓${NC} GitHub CLI authenticated"
else
    echo -e "${YELLOW}⚠${NC} GitHub CLI not authenticated (run: gh auth login)"
fi

# ────────────────────────────────────────────────────────────────────────────────
# Verify Network Connectivity
# ────────────────────────────────────────────────────────────────────────────────
echo ""
echo -e "${BLUE}► Checking package registry connectivity...${NC}"

# Test PyPI access
if timeout 5 curl -s -o /dev/null -w "%{http_code}" https://pypi.org | grep -q "200\|301\|302"; then
    echo -e "${GREEN}✓${NC} PyPI (pypi.org) accessible"
else
    echo -e "${RED}✗${NC} PyPI not accessible"
fi

# Test npm registry access
if timeout 5 curl -s -o /dev/null -w "%{http_code}" https://registry.npmjs.org | grep -q "200\|301\|302"; then
    echo -e "${GREEN}✓${NC} npm registry (registry.npmjs.org) accessible"
else
    echo -e "${RED}✗${NC} npm registry not accessible"
fi

# Test GitHub access
if timeout 5 curl -s -o /dev/null -w "%{http_code}" https://github.com | grep -q "200\|301\|302"; then
    echo -e "${GREEN}✓${NC} GitHub (github.com) accessible"
else
    echo -e "${RED}✗${NC} GitHub not accessible"
fi

# ────────────────────────────────────────────────────────────────────────────────
# Display Quick Reference
# ────────────────────────────────────────────────────────────────────────────────
echo ""
echo -e "${BLUE}► Package installation commands:${NC}"
echo ""
echo -e "${GREEN}Python packages:${NC}"
echo -e "  ${YELLOW}uv pip install <package>${NC}       # Install with UV (fast)"
echo -e "  ${YELLOW}pip3 install <package>${NC}         # Install with pip"
echo -e "  ${YELLOW}cd backend && uv pip install -r requirements.txt${NC}"
echo ""
echo -e "${GREEN}Node.js packages:${NC}"
echo -e "  ${YELLOW}npm install <package>${NC}          # Install from npm registry"
echo -e "  ${YELLOW}npm install -g <package>${NC}       # Install globally"
echo -e "  ${YELLOW}cd frontend && npm install${NC}     # Install from package.json"
echo ""
echo -e "${GREEN}Git operations:${NC}"
echo -e "  ${YELLOW}git clone git@github.com:user/repo.git${NC}   # SSH (if keys forwarded)"
echo -e "  ${YELLOW}git clone https://github.com/user/repo.git${NC} # HTTPS"
echo ""

# ────────────────────────────────────────────────────────────────────────────────
# Verify Package Managers
# ────────────────────────────────────────────────────────────────────────────────
echo -e "${BLUE}► Package manager status:${NC}"

if command -v uv &> /dev/null; then
    echo -e "${GREEN}✓${NC} UV: $(uv --version)"
else
    echo -e "${YELLOW}⚠${NC} UV not found"
fi

if command -v npm &> /dev/null; then
    echo -e "${GREEN}✓${NC} npm: $(npm --version)"
else
    echo -e "${YELLOW}⚠${NC} npm not found"
fi

if command -v python3 &> /dev/null; then
    echo -e "${GREEN}✓${NC} Python: $(python3 --version)"
else
    echo -e "${YELLOW}⚠${NC} Python not found"
fi

echo ""
echo -e "${GREEN}✓ Connectivity verification complete${NC}"
echo ""
